const map=L.map("map",{zoomControl:true}).setView([44.2,-73.1],8);
const framesLayer=L.layerGroup().addTo(map),objectsLayer=L.layerGroup().addTo(map),tracksLayer=L.layerGroup().addTo(map);
let manifest,frames=[],frameBounds=null,featuresByTime={},playing=false,timer=null;const times=[];
const fmt=v=>v==null||Number.isNaN(Number(v))?"—":Number(v).toFixed(1);
Promise.all([fetch("data/manifest.json").then(r=>r.json()),fetch("data/objects.geojson").then(r=>r.json()),fetch("data/frames.json").then(r=>r.json())]).then(([m,g,fd])=>{
 manifest=m;frames=fd.frames||[];frameBounds=fd.bounds;document.getElementById("subtitle").textContent=m.case_id+" • "+m.radar_site+" • "+m.scan_times_utc.length+" scans • "+m.track_ids.length+" tracks";
 g.features.forEach(x=>(featuresByTime[x.properties.timestamp]??=[]).push(x));times.push(...m.scan_times_utc);
 if(frameBounds)map.fitBounds(frameBounds,{padding:[20,20]});const s=document.getElementById("slider");s.max=Math.max(0,times.length-1);s.addEventListener("input",e=>render(+e.target.value));document.getElementById("play").onclick=toggle;render(0);
}).catch(e=>document.getElementById("subtitle").textContent="Viewer data not found: "+e);
function render(i){if(!times.length)return;const ts=times[i];document.getElementById("time").textContent=new Date(ts).toLocaleString()+" ("+ts+")";renderRadar(ts);renderObjects(ts)}
function renderRadar(ts){framesLayer.clearLayers();const f=frames.find(x=>x.timestamp===ts);if(!f||!frameBounds)return;L.imageOverlay("data/"+f.file,frameBounds,{opacity:.78,interactive:false}).addTo(framesLayer)}
function renderObjects(ts){objectsLayer.clearLayers();(featuresByTime[ts]||[]).forEach(f=>{const p=f.properties,layer=L.geoJSON(f,{style:{color:"#39b5ff",fillOpacity:.25,weight:2}}).addTo(objectsLayer);layer.bindTooltip("Object "+p.track_id+" • "+fmt(p.max_reflectivity_dbz)+" dBZ",{sticky:true});layer.on("mouseover",()=>showObject(f));layer.on("click",()=>showObject(f))});renderTracks(ts)}
function renderTracks(ts){tracksLayer.clearLayers();const by={};Object.values(featuresByTime).flat().forEach(f=>{const p=f.properties;if(p.timestamp>ts)return;(by[p.track_id]??=[]).push(f)});Object.values(by).forEach(fs=>{fs.sort((a,b)=>a.properties.timestamp.localeCompare(b.properties.timestamp));if(fs.length>1)L.polyline(fs.map(f=>[f.properties.centroid_lat,f.properties.centroid_lon]),{color:"#9aa8b5",weight:3,opacity:.7}).addTo(tracksLayer)})}
function showObject(f){const p=f.properties;document.getElementById("objectTitle").textContent="Track "+p.track_id+" • "+new Date(p.timestamp).toLocaleTimeString();document.getElementById("prob").textContent=p.probability_30min==null?"N/A":fmt(p.probability_30min)+"%";const vals=[["Max Z",fmt(p.max_reflectivity_dbz)+" dBZ"],["Mean Z",fmt(p.mean_reflectivity_dbz)+" dBZ"],["Area",fmt(p.area_km2)+" km²"],["Length",fmt(p.length_km)+" km"],["Width",fmt(p.width_km)+" km"],["Motion",fmt(p.motion_speed_kt)+" kt"],["Direction",fmt(p.motion_direction_deg)+"°"],["Z trend",fmt(p.reflectivity_trend_dbz_per_hr)+" dBZ/hr"]];document.getElementById("metrics").innerHTML=vals.map(x=>'<div class="metric">'+x[0]+'<b>'+x[1]+'</b></div>').join("");document.getElementById("drivers").textContent="Radar/object diagnostics are staged for scoring. Environmental fields and trained probabilities will populate this same time-indexed record."}
function toggle(){playing=!playing;document.getElementById("play").textContent=playing?"❚❚ Pause":"▶ Play";if(playing)tick();else clearTimeout(timer)}
function tick(){if(!playing)return;const s=document.getElementById("slider");s.value=(+s.value+1)%times.length;render(+s.value);timer=setTimeout(tick,600)}
document.getElementById("popout").onclick=()=>window.open("probability.html","snowSquallProbability","width=1100,height=760");